[general]
visual_mode = "Night"

[appearance.blocks]
and         = "0x000011"
or          = "0x001100"
xor         = "0x110000"
nand        = "0x110000"
nor         = "0x110000"
xnor        = "0x110000"
switch      = "0x110000"
button      = "0x110000"
tick_button = "0x110000"
light       = "0x110000"

[appearance.wires]
general  = "0x000000"
crossing = "0x000000"
generic  = "0x000000"
testing  = "0x000000"


[keybinds.blocks]
AND = "ctrl + a"
OR = "ctrl + a"
XOR = "ctrl + a"
NAND = "ctrl + a"
NOR = "ctrl + a"
XNOR = "ctrl + a"
SWITCH = "ctrl + a"
BUTTON = "ctrl + a"
TICK_BUTTON = "ctrl + a"
LIGHT = "ctrl + a"

