# -------------------- General --------------------
[general.general]
visual_mode = "Night"

[general.files]
save_path = "/abc"
open_path = "/edf"

# -------------------- Appearance --------------------
[appearance.blocks]
and = "0xff8e66"
or = "0x40ffcf"
xor = "0x55ffcd"
nand = "0xff2d12"
nor = "0x613760"
xnor = "0xf981ff"
switch = "0x558cff"
button = "0xa5ff53"
tick_button = "0x64ff3a"
light = "0xff7949"

[appearance.wires]
general = "0x488dff"
crossing = "0x1efff7"
generic = "0xff4eec"
testing = "0x6affdb"

[appearance.text]
font_size = "12px"
font_family = "12px"

# -------------------- Keybinds --------------------
[keybind.blocks]
and = "ctrl + a"
or = "ctrl + a"
xor = "ctrl + a"
nand = "ctrl + a"
nor = "ctrl + a"
xnor = "ctrl + a"
switch = "ctrl + a"
button = "ctrl + a"
tick_button = "ctrl + a"
light = "ctrl + a"

[keybind.placement]
single_place = "ctrl + s + p"
area_place = "ctrl + a + p"
move = "ctrl + m"

[keybind.connection]
simple = "ctrl + s"
tensor = "ctrl + t"

[keybind.selection]

[keybind.interactive]
state_changer = "ctrl + s + c"

