[general]
visual_mode = "Night"

[appearance.blocks]
and         = "0x000011"
or          = "0x001100"
xor         = "0x110000"
nand        = "0x110000"
nor         = "0x110000"
xnor        = "0x110000"
switch      = "0x110000"
button      = "0x110000"
tick_button = "0x110000"
light       = "0x110000"

[appearance.wires]
general  = "0x000000"
crossing = "0x000000"
generic  = "0x000000"
testing  = "0x000000"


[keybinds.blocks]
and         = "ctrl + a"
or          = "ctrl + a"
xor         = "ctrl + a"
nand        = "ctrl + a"
nor         = "ctrl + a"
xnor        = "ctrl + a"
switch      = "ctrl + a"
button      = "ctrl + a"
tick_button = "ctrl + a"
light       = "ctrl + a"

[keybind.placement]
single_place = "ctrl + s + p"
area_place   = "ctrl + a + p"
move         = "ctrl + m"

[keybind.connection]
simple = "ctrl + s"
tensor = "ctrl + t"

[keybind.selection]

[keybind.interactive]
state_changer = "ctrl + s + c"
