name: Coverity Scan

on:
  workflow_dispatch

permissions: 
  contents: read

jobs:
  coverity:
    runs-on: ubuntu-latest
    env:
      CC: gcc
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install Dependencies
      run: |
            sudo apt update
            sudo apt install -y --no-install-recommends build-essential gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev

    - name: Setup `wasmtime`
      uses: bytecodealliance/actions/wasmtime/setup@v1

    - uses: libsdl-org/setup-sdl@main
      id: sdl
      with:
        install-linux-dependencies: true
        version: 3-latest
        version-sdl-image: 3-latest

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.2
      with:
        version: 1.4.309.0
        cache: true

    - name: Configure using CMake
      run: cmake
               -DCMAKE_BUILD_TYPE=Debug
               -DCONNECTION_MACHINE_BUILD_TESTS=OFF
               -DCONNECTION_MACHINE_BUILD_APP=ON
               -B ${{github.workspace}}/build

    - uses: vapier/coverity-scan-action@v1
      with:
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
        command: make -C ${{github.workspace}}/build
